name: Compilar para iOS (Cortesía de GitHub)

on:
  push:
    branches: [ main ] # Se activa al subir cambios
  workflow_dispatch: # Botón manual en la web

jobs:
  build:
    runs-on: macos-latest # ¡Aquí pedimos el Mac prestado a GitHub!
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      - name: Sincronizar Capacitor iOS
        run: |
          npx cap sync ios

      - name: Compilar App (.app)
        run: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Debug -allowProvisioningDeviceRegistration -allowProvisioningUpdates CODE_SIGNING_ALLOWED=NO

      - name: Subir archivo final
        uses: actions/upload-artifact@v4
        with:
          name: App-iOS-Alannia
          path: ios/App/DerivedData/Build/Products/Debug-iphonesimulator/App.app