name: Compilar para iOS (Cortesía de GitHub)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      - name: Preparar carpeta web
        run: mkdir -p www

      - name: Forzar Regeneración Limpia de iOS en Mac
        run: |
          rm -rf ios
          npx cap add ios
          npx cap sync ios

      - name: Compilar App (.app)
        run: |
          cd ios/App
          xcodebuild -resolvePackageDependencies \
            -project App.xcodeproj \
            -scheme App
          xcodebuild \
            -project App.xcodeproj \
            -scheme App \
            -configuration Debug \
            -destination 'generic/platform=iOS Simulator' \
            -derivedDataPath DerivedData \
            CODE_SIGNING_ALLOWED=NO

      - name: Subir archivo final
        uses: actions/upload-artifact@v4
        with:
          name: App-iOS-Alannia
          path: ios/App/DerivedData/Build/Products/Debug-iphonesimulator/App.app
