name: Compilar para iOS (Cortesía de GitHub)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20  # Actualizado para evitar avisos de deprecación
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      - name: Instalar entorno de iOS para Capacitor
        run: npm install @capacitor/ios

      - name: Crear y Sincronizar Plataforma iOS
        run: |
          npx cap add ios
          npx cap sync ios

      - name: Compilar App (.app)
        run: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Debug -allowProvisioningDeviceRegistration -allowProvisioningUpdates CODE_SIGNING_ALLOWED=NO

      - name: Subir archivo final
        uses: actions/upload-artifact@v4
        with:
          name: App-iOS-Alannia
          path: ios/App/DerivedData/Build/Products/Debug-iphonesimulator/App.app